// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// predict_cpp
NumericVector predict_cpp(const List& gam_obj, const NumericVector& pars);
RcppExport SEXP _testObj_predict_cpp(SEXP gam_objSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type gam_obj(gam_objSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_cpp(gam_obj, pars));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_testObj_predict_cpp", (DL_FUNC) &_testObj_predict_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_testObj(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
