# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_cpp <- function(gam_obj, pars) {
    .Call(`_testObj_predict_cpp`, gam_obj, pars)
}

