# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_cpp_with_gam_obj <- function(gam_obj, pars) {
    .Call(`_testObj_predict_cpp_with_gam_obj`, gam_obj, pars)
}

predict_cpp_external_closure <- function(pars) {
    .Call(`_testObj_predict_cpp_external_closure`, pars)
}

predict_cpp_with_closure <- function(pars, f) {
    .Call(`_testObj_predict_cpp_with_closure`, pars, f)
}

